-env:
  - global:
    -'FTP_USER=kristinadamayantiii'
    -'FTP_PASS=kristina26'

    script:
      -"curl -u $FTP_PASS ftp://files.000webhost.com
      -Q 'mkd public_html/praktek=4c'"

      
      -"curl -T halo.php -u $FTP_USER;$FTP_PASS ftp://files.000webhost.com"